modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="instantunify"
version="1.0.2"
displayName="InstantUnify"
displayURL="https://www.curseforge.com/minecraft/mc-mods/instantunify"
credits="Thanks for this example mod goes to Java"
authors="KidsDontPlay"
description='''
Unifies oredicted items automatically
'''

[[dependencies.instantunify]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.instantunify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"
